import { Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar";
import Footer from "@/Components/Footer";

const OutfitFonts = Outfit({
 
  subsets: ["latin"],
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${OutfitFonts.className} h-full antialiased`}
    >
      <body>
        <Navbar />
        <main className="max-w-7xl mx-auto">{children}</main>
        <Footer />
        </body>
    </html>
  );
}
